---
title: "Soak Time Map"
author: "Sydney Collins"
date: "2024-05-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

---
title: "NAFO Divisions"
author: "Sydney Collins"
date: "2023-12-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load Packages and Data}
library(maps)
library(ggforce)
library(RColorBrewer)
library(viridis)
library(marmap)
library(tidyverse)
library(patchwork)
library(rgdal)
library(scales)
#library(legendMap)
require(gridExtra)
require(raster)
require(grid)
library(ggspatial)
library(sf)

Canada <- subset(map_data("world"), map_data("world")$region == "Canada") %>%
  filter(long > -60, lat > 46) %>%
  filter(long < -51, lat < 52.3)

NAFO <- st_read("data/NAFO_Divisions_SHP/NAFO_Divisions_2021_line_enclosed.shp")
  # filter(long > -60, lat > 46) %>%
  # filter(long < -51, lat < 52.3)

bathy <- getNOAA.bathy(lon1 = -51, lon2 = -60, lat1 = 52.3, lat2 = 46, resolution = 1, keep = T)
bat_xyz <- as.xyz(bathy)
bat_water <- bat_xyz %>% subset(V3 < 0)
```


```{r Maps}
#Main map
p1 <- ggplot() +
  geom_tile(data = bat_water, aes(x = V1, y = V2, fill = V3)) +
  scale_fill_gradient2(name = "Depth (m)", low = "dodgerblue4", mid = "gainsboro", high="darkgreen") +
  geom_sf(data = NAFO, colour = "black", fill = NA) +
  geom_polygon(data = Canada, aes(x = long, y = lat, group = group), fill = "grey50") +
  annotate("point", cex = 2, y = c(48.086010, 49.447928), x = c(-52.895682, -53.958540), colour = "red") +
  annotate("text", cex = 2.5, y = c(48.086010, 49.447928), x = c(-52.2, -53.0), label = c("Bay de Verde", "Musgrave Harbour")) +
  annotate("text", cex = 3, x = c(-53, -51.8, -55.7), y = c(50, 47.5, 46.5), label = c("3K", "3L", "3Ps")) +
  scale_y_continuous(expand = c(0, 0),
                     name = "Latitude",
                     limits = c(46, 52.3)) +
  scale_x_continuous(expand = c(0, 0),
                     name = "Longitude",
                     limits = c(-60, -51)) +
  theme_classic() +
  theme(
    panel.background = element_rect(fill = 'grey50'),
    text = element_text(size = 12),
    axis.text = element_text(colour = "black"), 
    axis.title=element_blank(),
    legend.margin = margin(0, 0, 0, 0),
    legend.box.margin = margin(-5, -5, -5, -5)
  ) +
  annotation_scale(location = "br", width_hint = 0.3, height = unit(0.5, "cm"), style = "ticks")

p1
```

```{r}
world_map <- map_data("world")

pol <- data.frame(xmin = -60, xmax = -39, ymin = 41 ,ymax = 56)

p2 <- ggplot() +
  geom_map(data = world_map, map = world_map, aes(long, lat, map_id = region), color = "black", fill = "lightgray", size = 0.1) +
  geom_rect(data = pol, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red", size = 1, linetype = 1) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), axis.text.x = element_blank(), axis.text.y = element_blank(), axis.ticks = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), plot.margin = unit(c(-1,-1,-1,-1),"mm"))

p2

tiff(filename = "figures/Fig1.tif", units = "mm", width = 180, height = 150, res = 300)
grid.newpage()
v1<-viewport(width = 1, height = 1, x = 0.5, y = 0.5) #plot area for the main map
v2<-viewport(width = 0.25, height = 0.18, x = 0.65, y = 0.86) #plot area for the inset map
print(p1,vp=v1) 
print(p2,vp=v2)
dev.off()
```

