---
title: "Soak Time and Duration"
author: "Jessika Lamarre, Robert Blackmore, Sydney Collins"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load packages and Data}
rm(list = ls())
library(tidyverse)
library(rstatix)
library(ggpubr)
library(emmeans)
library(DHARMa)
library(glmmTMB)
library(lubridate)
library(data.table)
library(doBy)
library(ggeffects)
library(FactoMineR)
library(factoextra)
library(viridis)
library(patchwork)
library(brglm)
library(scales)

#Setting up main datasets
####Metadata####
metadata <- read.csv("data/Main_herring_fishery_2024 - Metadata.csv", na.strings = "") %>%
  mutate(Cloud_cover = ifelse(
      Prevailing_weather_cond %like% "cloudy" |
        Prevailing_weather_cond %like% "Cloudy" |
        Prevailing_weather_cond %like% "overcast" |
        Prevailing_weather_cond %like% "Overcast" |
        Prevailing_weather_cond %like% "Rain",
      "Cloudy",
      ifelse(
        Prevailing_weather_cond %like% "clear" |
          Prevailing_weather_cond %like% "no cloud" |
          Prevailing_weather_cond %like% "Clear" |
          Prevailing_weather_cond %like% "sunny" |
          Prevailing_weather_cond %like% "Sunny",
        "Clear",
        ifelse(Prevailing_weather_cond == "Unknown", NA, "Cloudy")
      )
  )) %>%
  mutate(Fog = ifelse(
      Prevailing_weather_cond %like% "fog" == TRUE |
        Prevailing_weather_cond %like% "Fog" == TRUE,
      "Fog",
      "NoFog"
    )) %>%
  mutate(Rain = ifelse(
      Prevailing_weather_cond %like% "rain" |
        Prevailing_weather_cond %like% "Rain",
      "Rain",
      "NoRain"
    )) %>%
  mutate(Ocean_cond = ifelse(
      Prevailing_weather_cond %like% "calm" |
        Prevailing_weather_cond %like% "Calm",
      "Calm",
      ifelse(
        Prevailing_weather_cond %like% "rough" |
          Prevailing_weather_cond %like% "choppy" |
          Prevailing_weather_cond %like% "lop" |
          Prevailing_weather_cond %like% "swell",
        "Rough",
        NA
      )
    )) %>%
  mutate(Wind = ifelse(Wind_speed < 12, "LowWind", "Windy")) %>%
  drop_na(Observers, Wind) %>%
  mutate_at(c("Port", "Trip_ID", "Soak_duration", "Wind_direction_set", "Wind_direction", "Cloud_cover", "Fog", "Rain", "Ocean_cond", "Wind"), as.factor)

####Herring Morphometrics Data####
morpho.data <- read.csv("data/Main_herring_fishery_2024 - Herring_sampling.csv", na.strings = "NA") %>%
  mutate_at(1:3, as.factor) %>%
  drop_na()

####Full Catch Data####
main.data <- read.csv("data/Main_herring_fishery_2024 - Bird_catch_BothSites2.csv",
                      na.strings = "NA") %>%
  mutate(Total_catch_number = as.numeric(Total_catch_number)) %>%
  mutate(Total_catch_wt_kg =
           as.numeric(ifelse(
             is.na(Total_catch_wt_kg) == T & Port == "BdV",
             (Total_catch_number * 271) / 1000,
             Total_catch_wt_kg
           ))) %>%
  mutate(Time_setting = as.POSIXct(Time_setting, format = "%m/%d/%Y %H:%M:%S")) %>%
  mutate(Time_hauling = as.POSIXct(Time_hauling, format = "%m/%d/%Y %H:%M:%S")) %>%
  mutate(yDate = yday(Time_hauling)) %>%
  mutate(Soak_duration = as.numeric(Time_hauling - Time_setting)) %>%
  mutate_at(7:35, as.numeric) %>%
  mutate(Bird_time = as.numeric(as.ITime(Time_hauling))/60/60) %>%
  mutate(Birds = rowSums(.[17:34])) %>%
  mutate(Surface_feeders = rowSums(.[17:23])) %>%
  mutate(Divers = rowSums(.[24:31])) %>%
  mutate(Bycatch_sum = rowSums(.[13:16])) %>%
  left_join(
    metadata %>% dplyr::select(
      Trip_ID,
      Wind_speed,
      Wind_direction,
      Cloud_cover,
      Fog,
      Rain,
      Ocean_cond
    )
  ) %>%
  mutate_at(1:4, as.factor)

####Summed Catch Data####
#Catch dataset with individual nets summed per trip
sum.data <- main.data %>%
  filter(!(Trip_ID %like% "MH_05" & Net_group == "b")) %>%
  filter(!(Trip_ID %like% "MH_09" & Net_group == "b")) %>%
  group_by(
    Port,
    Trip_ID,
    Net_treatment,
    yDate,
    Cloud_cover,
    Fog,
    Rain,
    Ocean_cond,
    Wind_direction
  ) %>%
  summarise(
    Wind_speed = mean(Wind_speed, na.rm = T),
    Total_target_catch_number = sum(Total_catch_number, na.rm = T),
    Total_target_catch_kg = sum(Total_catch_wt_kg, na.rm = T),
    Net_area_m2 = sum(Total_net_area_m2, na.rm = T),
    Soak_duration = mean(Soak_duration, na.rm = T),
    Bird_time = mean(Bird_time, na.rm = T),
    Birds = sum(Birds, na.rm = T),
    Surface_feeders = sum(Surface_feeders, na.rm = T),
    Divers = sum(Divers, na.rm = T),
    Bycatch_sum = sum(Bycatch_sum, na.rm = T)
  ) %>%
  ungroup() %>%
  mutate(Wind_speed = as.numeric(gsub("NaN", NA, Wind_speed))) %>%
  mutate(Bycatch_rate = as.numeric(Bycatch_sum / Soak_duration / Net_area_m2)) %>%
  mutate(Scaled_weight = as.numeric(Total_target_catch_kg / Net_area_m2)) %>%
  mutate(Catch_rate = as.numeric(Total_target_catch_kg / Net_area_m2 / Soak_duration)) %>%
  mutate(Net_treatment = factor(Net_treatment, levels = c("24h", "12_night", "12_day"))) %>%
  mutate(Bycatch_species = as.factor(ifelse(Trip_ID == "MH_15", "Birds", "Fish"))) %>%
  mutate(Bird_time_cat = as.factor(ifelse(Bird_time < 12, "Morning", "Afternoon"))) %>%
  mutate(Birds = ifelse(Birds == 0 & Surface_feeders == 0 & Divers == 0, NA, Birds)) %>%
  mutate(Surface_feeders = ifelse(Birds == 0 & Surface_feeders == 0 & Divers == 0, NA, Surface_feeders)) %>%
  mutate(Divers = ifelse(Birds == 0 & Surface_feeders == 0 & Divers == 0, NA, Divers))
```

```{r Morphometric Summary Stats}
summaryBy(Sample_herring_wt_g ~ Port, data = morpho.data)
summaryBy(Sample_herring_wt_g ~ Port + Net_treatment, data = morpho.data)
summaryBy(Sample_herring_FK_cm ~ Port + Net_treatment, data = morpho.data)
```

```{r Summary Stats}
#Sample Size
table(sum.data$Net_treatment, sum.data$Port)

#Sample sizes and summary of treatments
summaryBy(Soak_duration ~ Net_treatment, data = sum.data, FUN = c(length, mean, sd, min, max))

#Herring Catch summary (Table S1)
summaryBy(Total_target_catch_number ~ Net_treatment + Port, data = sum.data)
summaryBy(Total_target_catch_kg ~ Net_treatment + Port, data = sum.data)
summaryBy(Sample_herring_wt_g ~ Net_treatment + Port, data = morpho.data)
summaryBy(Sample_herring_FK_cm ~ Net_treatment + Port, data = morpho.data)

#Bird Sightings summary (Table S3)
summaryBy(NOGA + DCCO + Cormorant_sp + BLGU + ATPU + COMU + RAZO + COEI + BLKI + HERG + GBBG + RBGU + LBBG + ICGU + COTE ~ Port + Bird_time_cat, data = main.data %>% drop_na(16:33), FUN = sum)
```

```{r Catch Model}
#Check assumptions for Catch weight
jpeg(filename = "figures/CatchBoxplots.jpeg", width = 16, height = 10, units = "cm", res = 300)
ggplot(sum.data, aes(x = Net_treatment, y = Scaled_weight)) +
  scale_colour_manual(values = c("red", "blue")) +
  geom_boxplot(fill = "lightgrey", outliers = FALSE) +
  geom_jitter(aes(colour = Port)) +
  labs(x = "Soak Treatment", y = bquote("Scaled Target Catch Weight " ~(kg/m^2))) +
  scale_x_discrete(labels = c('Control','Reduced Night','Reduced Day')) +
  theme_classic() +
  theme(legend.position = "top")
dev.off()

#Clearly not normal, does contain 0s so Gamma not an option
hist(sum.data$Scaled_weight)

#Get summary stats
summaryBy(Scaled_weight ~ Net_treatment, data = sum.data, FUN = c(mean, median, sd))

#try model with Tweedie distribution
mod <- glmmTMB(Scaled_weight ~ Net_treatment + Port + (1|yDate), data = sum.data,
                family = tweedie(link = "log"))

#check model assumptions
sim1 <- simulateResiduals(mod, plot = T)
performance::check_collinearity(mod)
plotResiduals(sim1, form = sum.data$Net_treatment)
plotResiduals(sim1, form = sum.data$Port)
plotResiduals(sim1, form = sum.data$yDate)

#assumptions looks good, get model results
summary(mod)
Anova(mod)

#Post-hoc test
emmeans(mod, list(pairwise ~ Net_treatment), adjust = "bh")
```

```{r Catch Rate Model}
#Check assumptions for Catch weight
jpeg(filename = "figures/ScaledCatchBoxplots.jpeg", width = 16, height = 10, units = "cm", res = 300)
ggplot(sum.data, aes(x = Net_treatment, y = Catch_rate)) +
  scale_colour_manual(values = c("red", "blue")) +
  geom_boxplot(fill = "lightgrey", outliers = FALSE) +
  geom_jitter(aes(colour = Port)) +
  labs(x = "Soak Treatment", y = bquote("Scaled Target Catch Weight " ~(kg/m^2/h))) +
  scale_x_discrete(labels = c('Control','Reduced Night','Reduced Day')) +
  theme_classic() +
  theme(legend.position = "top")
dev.off()

#Clearly not normal, does contain 0s so Gamma not an option
hist(sum.data$Catch_rate)

#Get summary stats
summaryBy(Catch_rate ~ Net_treatment, data = sum.data, FUN = c(mean, median, sd))

#try model with Tweedie distribution
mod1 <- glmmTMB(Catch_rate ~ Net_treatment + Port + (1|yDate), data = sum.data,
                family = tweedie(link = "log"))

#check model assumptions
sim1.1 <- simulateResiduals(mod1, plot = T)
performance::check_collinearity(mod1)
plotResiduals(sim1.1, form = sum.data$Net_treatment)
plotResiduals(sim1.1, form = sum.data$Port)
plotResiduals(sim1.1, form = sum.data$yDate)

#assumptions looks good, get model results
summary(mod1)
Anova(mod1)

#Post-hoc test
emmeans(mod1, list(pairwise ~ Net_treatment), adjust = "bh")
```

```{r Bycatch Data}
summaryBy(Bycatch_sum ~ Net_treatment, data = sum.data %>% drop_na(Bycatch_sum), FUN = c(mean, sum, length))

#separating out the birds from the fish

bycatch_box <- ggplot(
  data = sum.data %>%
    mutate(Bycatch_sum = ifelse(Bycatch_species == "Birds", 3, Bycatch_sum)) %>%
    add_row(
      Port = "MH",
      Trip_ID = "MH_15",
      Net_treatment = "24h",
      yDate = 148,
      Bycatch_sum = 1,
      Bycatch_species = "Fish"
    ) %>%
    mutate(Net_treatment = factor(Net_treatment, levels = c("24h", "12_night", "12_day"))),
  aes(x = Net_treatment, y = Bycatch_sum)
) +
  geom_boxplot(fill = "lightgrey", outliers = FALSE) +
  geom_jitter(
    aes(colour = Port, pch = Bycatch_species),
    width = 0.3,
    height = 0,
    size = 2.5
  ) +
  theme_classic() +
  ylab("Bycatch (Number of Individuals)") +
  scale_x_discrete(labels = c('Control', 'Reduced Night', 'Reduced Day')) +
  scale_colour_manual(values = c("red", "blue")) +
  scale_shape_manual(values = c(2, 1), name = "Species") +
  xlab("Soak Treatment") +
  theme(legend.position = "top")

bycatchRate_line <- ggplot(
  data = sum.data %>%
    mutate(Bycatch_sum = ifelse(Bycatch_species == "Birds", 3, Bycatch_sum)) %>%
    mutate(Bycatch_rate = ifelse(Bycatch_species == "Birds", 3/682.777/36, Bycatch_rate)) %>%
    add_row(
      Port = "MH",
      Trip_ID = "MH_15",
      Net_treatment = "24h",
      yDate = 148,
      Soak_duration = 36,
      Bycatch_sum = 1,
      Bycatch_species = "Fish",
      Bycatch_rate = 1/682.2777/36
    ) %>%
    mutate(Net_treatment = factor(
      Net_treatment, levels = c("24h", "12_night", "12_day")
    )),
  aes(x = Soak_duration, y = Bycatch_rate)
) +
  geom_smooth(method = "loess", colour = "black") +
  scale_colour_manual(values = c("red", "blue")) +
  scale_shape_manual(values = c(2, 1), name = "Species") +
  geom_point(aes(colour = Port, pch = Bycatch_species), size = 2.5) +
  theme_classic() +
  xlab("Soak Duration (h)") +
  ylab(bquote(Bycatch ~ Rate ~ (Individuals / m^2 / h))) +
  coord_cartesian(ylim = c(0, max(sum.data$Bycatch_rate))) +
  theme(legend.position = "top")

jpeg(filename = "figures/Bycatch.jpeg", width = 16, height = 18, units = "cm", res = 300)
bycatch_box / bycatchRate_line + plot_annotation(tag_levels = "A") + plot_layout(guides = "collect") & theme(legend.position = "bottom")
dev.off()
```

```{r Bird Occurrence Model}
jpeg(filename = "figures/BirdsBoxplot.jpeg", width = 16, height = 10, units = "cm", res = 300)
ggplot(data = sum.data %>% drop_na(Birds), aes(x = Bird_time_cat, y = Birds)) +
  geom_boxplot(fill = "lightgrey") +
  scale_colour_manual(values = c("red", "blue")) +
  xlab("Timing of Haul and Resetting") +
  ylab("Number of Birds") +
  geom_jitter(aes(colour = Port)) +
  theme_classic() +
  theme(legend.position = "top")
dev.off()

ggplot(data = sum.data %>% drop_na(Birds), aes(x = Bird_time, y = Birds)) +
  geom_point(aes(colour = Port)) +
  scale_colour_manual(values = c("red", "blue")) +
  xlab("Time of Haul and Resetting") +
  ylab("Number of Birds") +
  theme_classic() +
  theme(legend.position = "top")

ggplot(data = sum.data) +
  geom_smooth(aes(x = Bird_time, y = Divers), method = "lm", colour = "black") +
  geom_smooth(aes(x = Bird_time, y = Surface_feeders), method = "lm", colour = "red", fill = "red") +
  theme_classic()

ggplot() +
  geom_boxplot(data = sum.data, aes(x = Ocean_cond, y = Wind_speed)) +
  theme_classic()

summaryBy(Birds + Divers + Surface_feeders ~ Bird_time_cat + Port, data = sum.data %>% drop_na(Birds), FUN = c(mean, median, sd, length))

bird.data <- sum.data %>% drop_na(Bird_time, Wind_speed, Fog)

birdmod <- glmmTMB(Birds ~ Bird_time + Port + Wind_speed + Fog + Scaled_weight + (1|yDate), 
                    data = bird.data, family = nbinom2(link = "log"))
#Check assumptions
sim2 <- simulateResiduals(birdmod, plot = T)
plotResiduals(sim2, form = bird.data$Bird_time)
plotResiduals(sim2, form = bird.data$Port)
plotResiduals(sim2, form = bird.data$Wind_speed)
plotResiduals(sim2, form = bird.data$Fog)
plotResiduals(sim2, form = bird.data$Scaled_weight)
performance::check_collinearity(birdmod1)

#Looks good, check model fit
summary(birdmod1)
Anova(birdmod1)

#Do the same thing for divers only
diversmod <- glmmTMB(Divers ~ Bird_time + Port + Wind_speed + Fog + Scaled_weight + (1|yDate), 
                    data = sum.data, family = nbinom2(link = "log"))

sim2.1 <- simulateResiduals(diversmod, plot = T)
plotResiduals(sim2.1, form = bird.data$Bird_time)
plotResiduals(sim2.1, form = bird.data$Port)
plotResiduals(sim2.1, form = bird.data$Wind_speed)
plotResiduals(sim2.1, form = bird.data$Fog)
plotResiduals(sim2.1, form = bird.data$Scaled_weight)
performance::check_collinearity(diversmod)

#Looks good, check model fit
summary(diversmod)
Anova(diversmod)

#And the same for surface feeders
sfmod <- glmmTMB(Surface_feeders ~ Bird_time + Port + Wind_speed + Fog + Scaled_weight + (1|yDate), 
                    data = sum.data, family = nbinom2(link = "log"))

sim2.2 <- simulateResiduals(sfmod, plot = T)
plotResiduals(sim2.2, form = bird.data$Bird_time)
plotResiduals(sim2.2, form = bird.data$Port)
plotResiduals(sim2.2, form = bird.data$Wind_speed)
plotResiduals(sim2.2, form = bird.data$Fog)
plotResiduals(sim2.2, form = bird.data$Scaled_weight)
performance::check_collinearity(sfmod)

#Looks good, check model fit
summary(sfmod)
Anova(sfmod)
```

```{r Random Forest - Weather}
library(caTools)
library(randomForest)

split <- sample.split(as.data.frame(sum.data), SplitRatio = 0.7)
train <- subset(as.data.frame(sum.data), split == "TRUE") %>%
  drop_na(Wind_direction) %>%
  mutate(Weather = as.factor(Weather)) %>%
  select(Weather, Cloud_cover,Fog,Rain,Ocean_cond,Wind_direction, Wind_speed)
test <- subset(as.data.frame(sum.data), split == "FALSE") %>%
  drop_na(Wind_direction) %>%
  mutate(Weather = as.factor(Weather)) %>%
  select(Weather, Cloud_cover,Fog,Rain,Ocean_cond,Wind_direction, Wind_speed)

set.seed(120)
classifier_RF = randomForest(x = train[-1], 
                             y = train$Weather, 
                             ntree = 500)
classifier_RF
plot(classifier_RF)

y_pred = predict(classifier_RF, newdata = test[-1])

confusion_mtx = table(test[,1], y_pred)
confusion_mtx

importance(classifier_RF)

varImpPlot(classifier_RF)
```

```{r Random Forest - Whole Model}
crf <- randomForest(Birds ~ Bird_time + Port + Scaled_weight + Cloud_cover + Fog + Rain + Ocean_cond + Wind_direction + Wind_speed, data = sum.data %>% drop_na(Cloud_cover, Wind_direction))

crf
plot(crf)
varImpPlot(crf)
```